### ISSUE TITLE
Bug: Cant connect wallet on desktop

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#103]
Unable to connect wallet on desktop. Get to the screen screenshotted below, and clicking MM doesnt trigger anything. Not sure about this one

<img width="1512" alt="Screen Shot 2023-04-02 at 8 01 29 PM" src="https://user-images.githubusercontent.com/93691906/229386147-0c461742-0605-44cd-a5a7-1968bcce8f59.png">

**Comment by salieflewis** [comment]
Hi @0xTranqui, have you tried refreshing the page and connecting again? I don't experience this issue on my end, not sure what I can do to troubleshoot this.

**Comment by 0xTranqui** [comment]
it worked on refresh, just wanted to call out that it even bugging out like this once is pointing out a potential issue

**Comment by salieflewis** [comment]
How would you suggest troubleshooting this?

**Comment by 0xTranqui** [comment]
@salieflewis just happened again
<img width="1512" alt="Screen Shot 2023-04-03 at 10 19 46 PM" src="https://user-images.githubusercontent.com/93691906/229670019-8a106022-4c07-44a5-9a09-31e9d916bcad.png">

im not sure. curious if its a rainbow kit bug we could ask ppl about, or if its potentially related to the mobile log in issue? never seen this bug before

**Comment by salieflewis** [comment]
Probably going to dump RK for ConnectKit in the hopes that this bug goes away and that the mobile connect is magically fixed. Thoughts?
