### ISSUE TITLE
QA : D+M - Proposal Voting incorrect styles

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#110]
I wasn't able to see the proposal voting flow until viewing @0xTranqui s loom today. The modal looks like there are many styles that are incorrect as per the designs. I'm not able to tell what they are exactly because I'm viewing a recording, but a glance [at the Figma](https://www.figma.com/file/dfDelPay4YPOf3DkZyuLqn/UI-Design?node-id=462%3A8510&t=nIbhB2c6td52KWzj-1) will make it obvious. 

What I can notice : 

- As per Max's feat request - there needs to be a selected state for the voting options as per this design
- This is an onchain transaction. The "voting" CTA button styling is wrong, it needs to be the primary/transaction style.
-The modal is missing its border
-The title "Voting" should be a header - I'm not sure if it is from the screenshot if we can double check
-The voting selectors are built in the wrong style, or they're attached to the wrong corner radius style. Not sure.
-Missing the "Reason for vote" title above comment input
-Missing border around comment input

Current deploy screenshot, next to the Figma design : 

<img width="1104" alt="Screenshot 2023-04-03 at 7 50 12 PM" src="https://user-images.githubusercontent.com/103976531/229651168-7221c2de-e6c3-452f-8263-7381b30f79ff.png">

**Comment by salieflewis** [comment]
https://testnet-flexible.vercel.app/

I sent you a NEO token on Goerli, so you should be able to view this modal now given the active props.

**Comment by losingmyego** [comment]
Somehow not seeing the option to vote on any of the active props

<img width="1700" alt="Screenshot 2023-04-04 at 9 40 07 AM" src="https://user-images.githubusercontent.com/103976531/229811164-29085c33-4bbe-4635-b1d0-3986b1014411.png">

**Comment by salieflewis** [comment]
Ahh, it is actually probably because you didn't have a token when they were created.

**Comment by losingmyego** [comment]
Still looking for an active prop to QA this flow :)

**Comment by salieflewis** [comment]
Here is a live prop that you should be able to vote on @losingmyego 

https://testnet.flexible.works/proposals
