### ISSUE TITLE
Feat: Missing "veto" button/state

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#116]
Sending screenshot of what it looks like to be able to veto an active proposal (when logged in as ff89de.eth) on nouns . build, vs what it looks like (no veto button) on Flexible atm.

Nouns . build:
<img width="1512" alt="Screen Shot 2023-04-04 at 8 38 18 AM" src="https://user-images.githubusercontent.com/93691906/229793967-6c619500-336f-4387-b9d9-a636d38835c2.png">

Flexible:
<img width="1512" alt="Screen Shot 2023-04-04 at 8 38 34 AM" src="https://user-images.githubusercontent.com/93691906/229794037-51d4531c-6a94-40ac-a207-b44dd804ff5a.png">

**Comment by losingmyego** [comment]
Additionally, have created a veto button that matches the "error" button style from the Switch Network CTA

[Figma Designs](https://www.figma.com/file/dfDelPay4YPOf3DkZyuLqn/UI-Design?node-id=985%3A5643&t=fUGIyvrAcwbwxjqV-1)

<img width="1145" alt="Screenshot 2023-04-04 at 9 43 28 AM" src="https://user-images.githubusercontent.com/103976531/229812796-bba6f6d6-4f02-4f9c-a977-9eb5c63bf5c0.png">

**Comment by salieflewis** [comment]
Closing in favor of #120
