### ISSUE TITLE
QA : D+M - Proposals - Incorrect formatting on proposal start / end times

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#118]
As per the designs and nouns.build best practices, the countdowns should be in a DAY|HR\MIN format, and not stating a blanket calendar date

Current designs :

<img width="416" alt="Screenshot 2023-04-04 at 9 58 42 AM" src="https://user-images.githubusercontent.com/103976531/229816512-90135134-8882-46ba-bf89-77ac1270a9df.png">

Figma : 

<img width="757" alt="Screenshot 2023-04-04 at 9 59 51 AM" src="https://user-images.githubusercontent.com/103976531/229816814-64cfe52f-2d0c-4c41-87f1-ffccf56e1c22.png">

**Comment by salieflewis** [comment]
I remember seeing that different states ask for different voting formats. Can you just confirm this and update that if that is the case in Frame #1976
