### ISSUE TITLE
Feat : D+M - Update Menu design

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#134]
Realized the menu CTAs were not mirroring the correct hierarchy for the user, so we gave them an update - which can be[ found here ](https://www.figma.com/file/dfDelPay4YPOf3DkZyuLqn/UI-Design?node-id=1034%3A10967&t=4ncMyaM9u2WMvRdg-1)

<img width="1691" alt="Screenshot 2023-04-07 at 10 52 47 AM" src="https://user-images.githubusercontent.com/103976531/230629363-383d5bca-2dab-4caf-9f1a-b300f5a23b99.png">

**Comment by salieflewis** [comment]
Resolved in #138
