### ISSUE TITLE
QA D+M - Update on-chain schema on proposal cards

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#139]
1. Label for propoal status should bet attached to the Body, not header
2. Border of label for proposal status should be attached to primary color in schema
3. "by name.eth' should be attached to Body text in schema
4. Numnber of votes for / against labels should be attached to the Caption text in schema
5. Number of votes for/against labels should not be at 50% opacity, Should be at 100% opacity.

____

Left is from the deploy, right is from the Figma

<img width="1644" alt="Screenshot 2023-04-07 at 11 36 30 AM" src="https://user-images.githubusercontent.com/103976531/230636394-b5ec8396-453a-4a2b-86be-08a8a748b659.png">

**Comment by salieflewis** [comment]
Hi, I think you're confusing me a bit cause the styles in the original Figma are not matching up to what you're wanting now.

<img width="448" alt="CleanShot 2023-04-07 at 11 39 13@2x" src="https://user-images.githubusercontent.com/37086973/230636811-67434bc5-7a68-4591-9849-0d9c0de43d6a.png">

According to the designs, every element of this card gets body text except for the vote numbers which are caption.

**Comment by losingmyego** [comment]
You are correct! Updated my request
