### ISSUE TITLE
QA : D+M -  Proposal page needs updating in the schema

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#140]
Lots to change. Was a lot to type in a list, so left comments on a screen comparison in Figma.

[QA Details in the Figma](https://www.figma.com/file/dfDelPay4YPOf3DkZyuLqn/UI-Design?node-id=1050%3A7421&t=MMIJOx6DyqkGgRvB-1)

_______

<img width="1937" alt="Screenshot 2023-04-07 at 11 56 07 AM" src="https://user-images.githubusercontent.com/103976531/230639097-20e6b4a8-2b21-4c88-ad6a-d20a9a043cc7.png">

**Comment by losingmyego** [comment]
The schema update is not completed. Both header text sizes and links are still not attached to the primary color.

<img width="953" alt="Screenshot 2023-04-17 at 1 22 27 PM" src="https://user-images.githubusercontent.com/103976531/232562074-b6c704ce-d56e-4738-9ca9-469b0c636da9.png">

**Comment by salieflewis** [comment]
In the coming PR this issue should be resolved for any proposal not using uncommon markdown syntax. The styles have to be adjusted individually so I went through and added what I think is often to come up.

`className={cn(
        props.className,
        "prose prose-a:text-primary prose-p:text-primary prose-headings:text-primary prose-em:text-primary prose-strong:text-primary body text-primary"
      )}
`
