### ISSUE TITLE
QA: update the voting threshold and voting snapshot with the VotesSection component

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/flexible#141]
On the default template, these items flex properly as shown below

<img width="366" alt="CleanShot 2023-04-07 at 15 35 02@2x" src="https://user-images.githubusercontent.com/37086973/230666934-861682d7-c574-46be-8301-e7798c41250f.png">

However, when using a font that takes up more space, the items wrap in an undesired fashion

<img width="405" alt="CleanShot 2023-04-07 at 15 36 04@2x" src="https://user-images.githubusercontent.com/37086973/230667004-1496f8c6-4a51-4b58-b103-7c4b24b0745e.png">

**Comment by salieflewis** [comment]
justify-between

<img width="1245" alt="CleanShot 2023-04-10 at 15 15 30@2x" src="https://user-images.githubusercontent.com/37086973/230978839-dc3c180d-72a1-4dec-b5be-161fe320bcc5.png">

gap-6

<img width="1247" alt="CleanShot 2023-04-10 at 15 16 46@2x" src="https://user-images.githubusercontent.com/37086973/230979069-fc6ae049-719c-45cd-bed5-5ebb9333b76a.png">

--

Pick your poision @losingmyego

**Comment by salieflewis** [comment]
And then here is with a bigger font, that previously wrapped

<img width="1235" alt="CleanShot 2023-04-10 at 15 19 22@2x" src="https://user-images.githubusercontent.com/37086973/230979529-eafe00a5-1970-40be-8cd6-01c7e8f58a02.png">


<img width="1249" alt="CleanShot 2023-04-10 at 15 18 44@2x" src="https://user-images.githubusercontent.com/37086973/230979415-66dbff0b-c164-4311-9d54-4dd2f55955a8.png">

**Comment by losingmyego** [comment]
so hard 🥲, lets go with justify-between

**Comment by salieflewis** [comment]
Lol, so there is actually one scenario where there is a badge and a vote button below. And in the scenario the votes tally section and the voting snapshot/threshold chunk look very far apart. So I think we left in the gap-6 approach. Is that okay?

**Comment by salieflewis** [comment]
But also, need to let the record state @0xTranqui that @losingmyego chose justify-between. That is the one I thought worked better too. (Aside from the issue I just mentioned above)

**Comment by salieflewis** [comment]
Closing this with `gap-6` as the implemented solution
