### ISSUE TITLE
Bug: fix the auction and hide triggers from being focused directly after being clicked

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/flexible#144]
<img width="159" alt="CleanShot 2023-04-10 at 16 15 22@2x" src="https://user-images.githubusercontent.com/37086973/230989754-e688b221-d498-4938-b1c5-27c1454b9f30.png">

Should look like this upon click 

<img width="161" alt="CleanShot 2023-04-10 at 16 15 44@2x" src="https://user-images.githubusercontent.com/37086973/230989830-c5cf92ea-6595-439a-98f5-8b3dab035be0.png">

**Comment by 0xTranqui** [comment]
i think the reason this is happening is because it is actually the same button that appears by itself and then in the modal? so it actually makes sense that its focused on click? maybe the expand click could add something into a handler to de focus the handler post click? cc @salieflewis
