### ISSUE TITLE
Feat: Theme Registry

### ISSUE THREAD

**Issue by E-Rick** [public-assembly/flexible#15]
This would involve: 

- [x]  integrating the theme editor 
- [x]  converting the hex values to rgb for tailwind, 
- [x]  connecting all the appropriate css variables to the registry
- [x] base drawer component (repurposed dialog from radix essentially)  
- [x] Color picker
- [x] Font dropdown
- [x] Drop shadow
- [x] Corner Radius

**Comment by salieflewis** [comment]
Removed 

- fonts from google fonts (because fonts are being pulled from ipfs)
