### ISSUE TITLE
Feat: Integrate Dao utils auctions

### ISSUE THREAD

**Issue by E-Rick** [public-assembly/flexible#16]
- [ ] Expose more of the necessary proposals and auction components in the package
- [ ] Setup the token explorer with the PA fallback image
- [ ] Setup the desktop auction drawer with the exported auction components
- [ ] Setup the mobile auction sheet with the exported auction components
- [ ] Restyled auction components 
- [ ] Bidders hover 
- [ ] Auction input field states
- [ ] Action button shadows
- [ ] Fix border radius color on the dropdown

**Comment by salieflewis** [comment]
@E-Rick can we merge this issue into issue #4
