### ISSUE TITLE
QA : Proposals :  "Suceeded" should be "Executed"?

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#161]
Wdyt? Should we utilize the established language?

 Succeeded feels weird, would prefer to default to Executed but lmk ur thoughts @salieflewis @0xTranqui 

<img width="587" alt="Screenshot 2023-04-17 at 1 07 35 PM" src="https://user-images.githubusercontent.com/103976531/232559330-65c7c641-811b-46eb-889b-f51e948c660b.png">

**Comment by losingmyego** [comment]
Gotchu - @salieflewis do you think the "Suceeded" label should be the same style as Active [primary], or the same as Pending [secondary]?

<img width="1111" alt="Screenshot 2023-04-18 at 12 00 53 AM" src="https://user-images.githubusercontent.com/103976531/232667929-4c73dfbf-5855-40c7-be1c-5a1f1ea5827a.png">

**Comment by salieflewis** [comment]
I believe right now it is the secondary style. Am I good to close this issue? @losingmyego

**Comment by losingmyego** [comment]
Yerrp
