### ISSUE TITLE
Bug: Add ability to queue a successful proposal

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/flexible#168]
If a proposal is in the `SUCCEEDED` state, one should be able to queue it such that it moves to the `EXECUTED` state.

**Comment by 0xTranqui** [comment]
idk if u did anything but i was just able to scucessfully queue this [prop](https://flexible.vercel.app/proposals/0xc1f915106d53d2dcca6a3516926acab37d0a32e1041b8e84dcc033527ea87e09) (which is now in queue state). note: it doesn not move into the "executed" state until the buffer period for veto is over (2 days i think), at which point it will be in the "executable" state, upon which execution would move it into "executed" state
