### ISSUE TITLE
Feat: Integrate Dao Utils Proposals

### ISSUE THREAD

**Issue by E-Rick** [public-assembly/flexible#17]
- [ ] Expose all of the proposal logic in the package for integration into the proposals page
- [ ] Create proposal statuses with theme vars
- [ ] Desktop UI - Proposal grid and index page 
- [ ] Mobile UI

**Comment by salieflewis** [comment]
@E-Rick can I go ahead and close this issue? 

1. All the proposal logic has been exposed from dao-utils
2. Proposal status is shown on each card (although not hooked up to theming variables)
3. Desktop UI is implemented
4. Mobile UI is implemented
