### ISSUE TITLE
Feat: Issues displaying newly minted tokens following auction settlement

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#174]
looks like we may need to update the data indexing that’s used to grab new token image and stuff since there is a pretty weird delay/error when u settle auction + mint new token. an intermediate route could just be having a placeholder “fetching new token” image appear in the in between phase after u settle an auction and before u can grab the new token image

**Comment by losingmyego** [comment]
hey friends! last critical - what we thinking here @0xTranqui @salieflewis

**Comment by salieflewis** [comment]
Will push a fix for this tomorrow!

**Comment by salieflewis** [comment]
Spent some time cranking on this today, results of which you can find [here](https://github.com/public-assembly/flexible/pull/194). I'm trying to avoid adding dynamic routing to the whole thing cause for some reason that feels like a large change (approach taken by Nouns Builder + Neokry's Nouns Site), but asking @gainor to take a peek and see if we can get this completed.

**Comment by 0xTranqui** [comment]
we currently have an auction (that received no bids) waiting to be settled. are we in a spot where we can screen record this to see if new code changes have addrssed the issue? I saw some of the previous work towards this was closed and not merged, but I know @salieflewis just pushed a bunch of new updates so wanted to check

**Comment by 0xTranqui** [comment]
just got some nice footage of the current acution settlement flow. tldr it still doesnt trigger the new token being focused on, but it looks like the token images are showing up much quicker than they were before which is great (before it took like multiple minutes before the new token image would appear, now is down to seconds)

link to loom: https://www.loom.com/share/2d360b7daf4d40be8db95ade6eb268a6
