### ISSUE TITLE
Bug: Issues with voting modal on mobile

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#181]
@salieflewis @losingmyego may have just uncovered another critical bug(s) (will defer the critical tag to yall) when trying to vote on mobile. 

1. the way the modal works you cannot access the vote button on the view its first presented in, and you are unable to scroll down to the vote button. 
2. when I was typing out my reason, I was unable to see the text area because my keyboard was blocking the entire screen, and had no ability to scroll the screen to uncover. cant rlly type/edit correctly without this

see screenshots below for what it looks like on flexible, plus comparisons to the nouns.build mobile vote flow that worked for me

flexible
![IMG_3761](https://github.com/public-assembly/flexible/assets/93691906/e40e1a62-2fed-4c74-81fb-054570a18015)
![IMG_3763](https://github.com/public-assembly/flexible/assets/93691906/1dec367b-c568-4d4f-9422-e10cda935f9b)

nouns build
![IMG_3765](https://github.com/public-assembly/flexible/assets/93691906/14c45d79-4d91-46a3-b3f9-11aa88dca0c9)

**Comment by losingmyego** [comment]
Yeah super interesting- I believe that's critical.

Adding two more screenshots on how nounsbuild handles it. Looks like the button gets covered a tad with the browser UI. Looks like they zoom in when you start typing a reason.

![image](https://github.com/public-assembly/flexible/assets/103976531/672d53f2-c16e-4fb7-8d8a-37de42246a15)

![image](https://github.com/public-assembly/flexible/assets/103976531/98428be5-cdee-426f-a185-71c955a630ee)

**Comment by losingmyego** [comment]
And here is Safari

![image](https://github.com/public-assembly/flexible/assets/103976531/21c88917-a210-42d1-8901-ccca7f869c93)

![image](https://github.com/public-assembly/flexible/assets/103976531/d01751de-7662-4e10-903c-8022c4f830b7)

**Comment by losingmyego** [comment]
@salieflewis i Can work on tweaking the design if needed. Lmk
