### ISSUE TITLE
Feat: OG Images

### ISSUE THREAD

**Issue by E-Rick** [public-assembly/flexible#22]
A PA designed dynamic OG card template perhaps using next??? 

Would be good for the tweet of successful vote as well.

**Comment by salieflewis** [comment]
@E-Rick is this a nice to have? I actually don't even know what this means if you could please provide more context about what this feature would be.

**Comment by E-Rick** [comment]
It's a nice to have. It's just the metadata for the dao site. 

An Open Graph image or OG image is the image that is displayed on social media accounts when you or someone else post a link to an article or a video from your website. It's a standard for displaying rich link previews on sites like fb, linkedin, pinterest or through sharing the link to the site through text etc... So I would image a simple image template for creating a dynamic social image with the DAO info.

This goes in the metadata tags. 

There's metadata for twitter cards and og images. Although twitter being more important. 

```
<meta name="twitter:card" content="<summary_large_image>" />
<meta name="twitter:site" content="<@twitterhandle>" />
<meta name="twitter:title" content="<proposal title>" />
<meta name="twitter:description" content="<headline>" />
<meta name="twitter:image" content="<image_url>" />
```

So if a user deploys a site and then shares a link to the site it would display a social card preview.

**Comment by salieflewis** [comment]
Thank you for this detailed explanation.
