### ISSUE TITLE
Feat: Add flow for creating a new platform index

### ISSUE THREAD

**Issue by salieflewis** [public-assembly/flexible#34]
i.e. what is found [here](https://etherscan.io/address/0x9a23AE640040e4d34E9e00E500003000017144F4#writeContract) when calling newPlatformIndex

**Comment by salieflewis** [comment]
Here is a video of the interaction as it exists now, I'll keep this issue open for UX, copy, or design input!

@0xTranqui @losingmyego 

https://user-images.githubusercontent.com/37086973/227045816-75f80800-7bcb-474e-814f-8cbd8db4c97f.mov

The original video was 65MB, don't @ me

**Comment by salieflewis** [comment]
My takeaway from your looms @0xTranqui was that the `ArrowUpRight` component should also be part of the 'Take Me To Vercel' link, and that also there needs to be more clarity surrounding what environment variables to put where.

Spoke about this yesterday briefly with @losingmyego but I will try to remove any unnecessary env vars from the required field as well as move NEXT_PUBLIC_PLATFORM_INDEX to the top.

@Valcoholics we need a single page of the documentation focused solely on configuring the appropriate environment variables. There is a place to put an external link on the Vercel deploy page which is where we would provide the route to the above.

**Comment by Valcoholics** [comment]
Managers of the contract is a later concern in the back of my head as well but added a page, the video will make the page shorter

**Comment by salieflewis** [comment]
Resolved with #69 

> Managers of the contract is a later concern in the back of my head as well but added a page, the video will make the page shorter

This is also facts though.
