### ISSUE TITLE
Bug: Auction Data doesnt come in until user connects wallet

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#37]
just noticed a small bug where the auction data on the main auction card seems to be coming from the user's wallet provider as opposed to the env variable rpc api. imagine this is a fairly easy change up to re route the query thru the apps rpc connection as opposed to the users wallet

not connected -- no auction data in main auction card
<img width="1512" alt="Screen Shot 2023-03-17 at 1 12 43 PM" src="https://user-images.githubusercontent.com/93691906/225973102-44f429a6-a732-4996-b990-901a33329acc.png">

after connecting -- auction data in main auction card
<img width="1512" alt="Screen Shot 2023-03-17 at 1 12 59 PM" src="https://user-images.githubusercontent.com/93691906/225973161-2dc63149-14d5-4667-9804-24fcdde953dd.png">

**Comment by breath-imager** [comment]
+1
