### ISSUE TITLE
QA : Auction - adjust artwork sizing on landing

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#61]
this could just be my browser but when I get to the home page the sizing of the components make it so there is a scroll.

i feel like the experience could be a lil simpler/cleaner if we reduced the sizing so that a user wont ever need to scroll on desktop to see everything? this just an idea. attached a screenshot to explain what im talking bout

cc @salieflewis 

<img width="1512" alt="Screen Shot 2023-03-22 at 6 11 55 PM" src="https://user-images.githubusercontent.com/93691906/227050090-0b6c76cd-82ac-4b28-aa01-5f92f8af6837.png">

**Comment by losingmyego** [comment]
Confirming the same issue on my end, for both desktop and mobile experience. Will create a new size suggestion in Figma and follow up shortly

**Comment by losingmyego** [comment]
We just need to make it so its not spilling out of the view port. This site shouldnt expand beyond 100VH. Will send it in a few

**Comment by losingmyego** [comment]
600x600 for the square seems to do well.[ Figma](https://www.figma.com/file/dfDelPay4YPOf3DkZyuLqn/UI-Design?node-id=968%3A5579&t=MSpGxVTSpwfMgLWD-1)

<img width="1023" alt="Screenshot 2023-04-04 at 12 31 16 AM" src="https://user-images.githubusercontent.com/103976531/229687489-245dc832-e85b-4e7a-b255-34f37b45ebda.png">

**Comment by 0xTranqui** [comment]
re opening because mobile still has issue where auction button overlaps auction data
