### ISSUE TITLE
QA : Desktop - Navigation :  Fix Hover State

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#76]
Missing Hover state for Navigation items. Should be attached to Tertiary color in the theme.

<img width="583" alt="Screenshot 2023-03-27 at 4 33 19 PM" src="https://user-images.githubusercontent.com/103976531/228059905-858713e4-8396-4533-8c96-a9d74dbca5c5.png">

**Comment by salieflewis** [comment]
Fixed with #99
