### ISSUE TITLE
QA : D+M - Auction / Global  : Incorrect "Active State' for form inputs

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#77]
Active state while typing in forms should be attached to the Primary color in theme. Currently it is tertiary.

<img width="366" alt="Screenshot 2023-03-27 at 4 35 16 PM" src="https://user-images.githubusercontent.com/103976531/228060572-637517db-cf03-4ed9-8d50-8819a75becc0.png">

<img width="1193" alt="Screenshot 2023-03-27 at 4 35 05 PM" src="https://user-images.githubusercontent.com/103976531/228060583-bdbf08c1-c4d4-49e6-abcc-f5ee6c1c6bff.png">

**Comment by salieflewis** [comment]
Resolved #93
