### ISSUE TITLE
QA : D+M - Auction : Missing Currency indicator in auction input

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#78]
It is confusing to have the ETH currency symbol dissapear when typing an amount to bid. The designs have it displaying while a user is entering in a bid. cc @E-Rick . I would suggest we display it or use suggestive formatting (aka I shouldn't be able to type in letter characters, only numbers).

<img width="366" alt="Screenshot 2023-03-27 at 4 35 16 PM" src="https://user-images.githubusercontent.com/103976531/228060957-1c78c497-0d58-4b98-aa54-ce43c239751c.png">

<img width="1424" alt="Screenshot 2023-03-27 at 4 39 59 PM" src="https://user-images.githubusercontent.com/103976531/228061273-d07d6b92-5152-4c93-8876-2ff0c0416189.png">

**Comment by salieflewis** [comment]
This specific detail is difficult to achieve. With the coming PR, I've updated the input to only accept numeric characters.

**Comment by losingmyego** [comment]
Beautiful, it looks great
