### ISSUE TITLE
QA: D+M- Onchain Theming: Incorrect starting typeface for "Caption" style

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#83]
Incorrect typeface for "Caption" on the default template. Should be Space Mono. IBM Plex Mono would work also. Literally any mono.

<img width="443" alt="Screenshot 2023-03-27 at 5 57 45 PM" src="https://user-images.githubusercontent.com/103976531/228076331-29491a08-8b8a-4ae0-a505-a2555bbcb34f.png">

**Comment by salieflewis** [comment]
Going to close this issue, cause it is actually referring to something else where the state of the theme editor doesn't reflect the actual font being used. This points to a larger problem with the editor that I would like to fix eventually.
