### ISSUE TITLE
Bug: No error report when clicking Create Index button when not logged in. 

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#86]
this is what it looks like when im not logged in and trying to create a new index. i dont get any feedback about the error which is confusing. i suspect we should either gate the "copy template" to require a user to be connected, or gate the landing page once u click "copy template" so you can progress before connecting (and u get auto booted back to the landing if u disconnect)

<img width="1512" alt="Screen Shot 2023-03-27 at 6 11 35 PM" src="https://user-images.githubusercontent.com/93691906/228078448-8119f0fa-4cd7-44e6-bb5d-be702736493c.png">

**Comment by 0xTranqui** [comment]
cc @salieflewis

**Comment by losingmyego** [comment]
Hmmm interesting - I think we should def do your 2nd suggestion and gate the landing page once you click "Copy our template"
