### ISSUE TITLE
Feat: Copy update suggestion 

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#87]
I think we should change "copy our template" to "copy site template." usage of the word "our" there gives me a lil weird vibes in terms of ownership. this template isnt anyones, its everyones ???

<img width="366" alt="Screen Shot 2023-03-27 at 6 13 35 PM" src="https://user-images.githubusercontent.com/93691906/228078765-f5708e29-4236-4a5b-989d-aaee1c80056a.png">

**Comment by 0xTranqui** [comment]
cc @Valcoholics @salieflewis

**Comment by losingmyego** [comment]
"Copy this template" is my suggestion

**Comment by losingmyego** [comment]
or even "Use this template" for the non techy people out there
