### ISSUE TITLE
QA : Proposals - Sort abilities

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#88]
Not sure if it was decided to leave out sort abilities for this build, but decided to surface that it was missing :) cc @salieflewis @E-Rick @0xTranqui 

<img width="718" alt="Screenshot 2023-03-27 at 6 14 02 PM" src="https://user-images.githubusercontent.com/103976531/228079117-73578aa6-9155-4e4f-a81c-43bbd7b39ecf.png">

**Comment by salieflewis** [comment]
Hey Neesh, I don't think this one is going to make the v1. Is it cool to update the Figma to reflect that? I think in future it would be cool to update by type, creating a more robust filtering mechanism. I'm sure you share the same desire.
