### ISSUE TITLE
QA : D+M - Proposals : Start time is static / not connected to data

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#89]
All the starting times look static, not sure if that's already an issue

<img width="1339" alt="Screenshot 2023-03-27 at 6 17 27 PM" src="https://user-images.githubusercontent.com/103976531/228079350-ae127eb0-beee-4d86-aafb-b5683b7dd899.png">

**Comment by salieflewis** [comment]
Resolved #93
