### ISSUE TITLE
Bug : Proposals page is not pulling recent data

### ISSUE THREAD

**Issue by losingmyego** [public-assembly/flexible#91]
Last two proposals for Public Assembly are not showing up on the current site build, there should be a total of 12 proposals.

<img width="1898" alt="Screenshot 2023-03-27 at 6 27 20 PM" src="https://user-images.githubusercontent.com/103976531/228080929-8b9c39ad-f29d-4d68-b2fd-903460bc2340.png">

**Comment by 0xTranqui** [comment]
hey yea its just a pagination thing, just bump need to bump the limit up. all 12 showing in this query

<img width="1512" alt="Screen Shot 2023-03-28 at 9 21 13 PM" src="https://user-images.githubusercontent.com/93691906/228402037-c4d6bd05-8745-493d-a9a7-09a0e047571b.png">
