### ISSUE TITLE
Feat: Improved button selected states on submit proposal modal 

### ISSUE THREAD

**Issue by 0xTranqui** [public-assembly/flexible#97]
tldr their currently is not great visual feedback on what choice a user is making when submitting a propsoal, which could lead to incorrect votes being submitted. adding a more obvious visual signal (ex: changing the background of the button when selected) could be a pretty easy way to clean this up, but other solutions could work as well. seems like a small + important fix to boost user confidence in the voting stage! recorded a [loom](https://www.loom.com/share/6044d5bdf6c74b9db9707ce231191fab) describing this in more details 

cc @salieflewis

**Comment by 0xTranqui** [comment]
cc @losingmyego as well

**Comment by losingmyego** [comment]
The selected option should be showing up as inverted [per the designs](https://www.figma.com/file/dfDelPay4YPOf3DkZyuLqn/UI-Design?node-id=462%3A8510&t=nIbhB2c6td52KWzj-1) @salieflewis @0xTranqui 

<img width="1184" alt="Screenshot 2023-04-03 at 7 04 25 PM" src="https://user-images.githubusercontent.com/103976531/229645291-2b303459-8f1f-49f6-8a58-dd0a58cdb481.png">

**Comment by salieflewis** [comment]
I realized that because the testnet build had been styled, you weren't able to do QA against it, thus unable to vote on props, and unable to to see/interact this modal. Closing this issue and dropping a new link in the other related issue.

[Link to testnet deploy ](https://testnet-flexible.vercel.app/)

**Comment by losingmyego** [comment]
@salieflewis Can you reference where the other related issue is, thanks
